//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHangCBNV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportInfo
    {
        public string Id { get; set; }
        public string IdSupply { get; set; }
        public string IdExportInfo { get; set; }
        public int IdCustomer { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Export Export { get; set; }
        public virtual ImportInfo ImportInfo { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
