//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHangCBNV.Model
{
    using QuanLyKhoHangCBNV.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class ImportInfo : BaseViewModel
    {
        //Id
        private string _Id;
        public string Id { get => _Id; set { _Id = value;  OnPropertyChanged(); } }
        //IdSupply
        private string _IdSupply;
        public string IdSupply { get => _IdSupply; set { _IdSupply = value; OnPropertyChanged(); } }
        //IdImport
        private string _IdImport;
        public string IdImport { get => _IdImport; set { _IdImport = value; OnPropertyChanged(); } }
        //Quantity
        private Nullable<int> _Quantity;
        public Nullable<int> Quantity { get => _Quantity; set { _Quantity = value; OnPropertyChanged(); } }
        //Import Price
        private Nullable<double> _ImportPrice;
        public Nullable<double> ImportPrice { get => _ImportPrice; set { _ImportPrice = value; OnPropertyChanged(); } }
        //Export Price
        private Nullable<double> _ExportPrice;
        public Nullable<double> ExportPrice { get => _ExportPrice; set { _ExportPrice = value; OnPropertyChanged(); } }
        //Status
        private string _Status;
        public string Status { get => _Status; set { _Status = value; OnPropertyChanged(); } }

        private Import _Import;
        public virtual Import Import { get => _Import; set { _Import = value; OnPropertyChanged(); } }
        private Supply _Supply;
        public virtual Supply Supply { get => _Supply; set { _Supply = value; OnPropertyChanged(); } }
    }
}
