//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHangCBNV.Model
{
    using QuanLyKhoHangCBNV.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Supply : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supply()
        {
            this.ExportInfoes = new HashSet<ExportInfo>();
            this.ImportInfoes = new HashSet<ImportInfo>();
        }
    
        public string Id { get; set; }
        //DisplayName
        private string displayName;
        public string DisplayName { get => displayName; set { displayName = value; OnPropertyChanged(); } }
        //IdMeasure
        private int idMeasure;
        public int IdMeasure { get => idMeasure; set { idMeasure = value; OnPropertyChanged(); } }
        //IdSupllier
        private int idSupplier;
        public int IdSupplier { get => idSupplier; set { idSupplier = value; OnPropertyChanged(); } }
        //QRCode
        private string qrCode;
        public string QRCode { get => qrCode; set { qrCode = value; OnPropertyChanged(); } }
        //BarCode
        private string barCode;
        public string BarCode { get => barCode; set { barCode = value; OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportInfo> ExportInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportInfo> ImportInfoes { get; set; }

        private Measure measure;
        public virtual Measure Measure { get => measure; set { measure = value; OnPropertyChanged(); } }
        private Supplier supplier;
        public virtual Supplier Supplier { get => supplier; set { supplier = value; OnPropertyChanged(); } }
    }
}
