//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHangCBNV.Model
{
    using QuanLyKhoHangCBNV.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class User : BaseViewModel
    {
        public int Id { get; set; }
        //DisplayName
        private string _DisplayName;
        public string DisplayName { get => DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }
        //UserName
        private string _UserName;
        public string UserName { get => _UserName; set { _UserName = value; OnPropertyChanged(); } }
        //Password
        private string _Password;
        public string Password { get => _Password; set { _Password = value; OnPropertyChanged(); } }
        //Role
        private int _IdRole;
        public int IdRole { get => _IdRole; set { _IdRole = value; OnPropertyChanged(); } }

        private UserRole _UserRole;
        public virtual UserRole UserRole { get => _UserRole; set { _UserRole = value; OnPropertyChanged(); } }
    }
}
