//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHangCBNV.Model
{
    using QuanLyKhoHangCBNV.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class User : BaseViewModel
    {
        public int Id { get; set; }
        //DisplayName
        private string displayName;
        public string DisplayName { get => displayName; set { displayName = value; OnPropertyChanged(); } }
        //UserName
        private string userName;
        public string UserName { get => userName; set { userName = value; OnPropertyChanged(); } }
        //Password
        private string password;
        public string Password { get => password; set { password = value; OnPropertyChanged(); } }
        //idrole
        private int idRole;
        public int IdRole { get => idRole; set { idRole = value; OnPropertyChanged(); } }
    
        private UserRole role;
        public virtual UserRole UserRole { get => role; set { role = value; OnPropertyChanged(); } }
    }
}
